stages:
  - build
  - test
  - docker
  - deploy

docker_build:
  stage: docker
  image: docker:26-cli
  services:
    - name: docker:26-dind
      alias: docker

  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - echo "USER=$REGISTRY_USER"
    - echo "PASS length=${#REGISTRY_PASSWORD}"
    - echo "$REGISTRY_PASSWORD" | docker login registry.datexis.com -u "$REGISTRY_USER" --password-stdin

  script:
    - docker build -t registry.datexis.com/caka7833/vllm_diagnose_prediction:latest .
    - docker push registry.datexis.com/caka7833/vllm_diagnose_prediction:latest